
import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { useLanguage, Link } from '../context/LanguageContext';
import { ArrowLeft } from 'lucide-react';

const Studio: React.FC = () => {
  const { language, t } = useLanguage();
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState('1:1');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { text: `An artistic vision of: ${prompt}. Cinematic lighting, highly detailed, futuristic aesthetic.` }
            ]
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio as any,
          }
        },
      });

      let imageUrl = null;
      if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64EncodeString = part.inlineData.data;
                imageUrl = `data:image/png;base64,${base64EncodeString}`;
                break;
            }
        }
      }

      if (imageUrl) {
        setGeneratedImage(imageUrl);
      } else {
        setError("No image generated by the system.");
      }
      
    } catch (err) {
      console.error(err);
      setError("AI generation failed. Please check your prompt or network.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-brand-dark pt-32 pb-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[120px] -z-10" />
      <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-purple-600/10 rounded-full blur-[120px] -z-10" />

      <div className="max-w-7xl mx-auto">
        <Link to="/" className="group inline-flex items-center gap-2 text-gray-500 hover:text-white transition-colors mb-12 font-mono text-xs uppercase tracking-widest bg-white/5 px-4 py-2 rounded-full border border-white/5">
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          {language === 'en' ? 'Back to Home' : '返回首页'}
        </Link>

        <div className="flex flex-col lg:flex-row gap-12 items-start">
          
          {/* Controls - Left Column */}
          <div className="w-full lg:w-1/3 space-y-8">
            <div className="space-y-2">
              <span className="text-blue-500 font-mono text-xs uppercase tracking-widest">Inspiration Terminal</span>
              <h1 className="text-4xl font-black text-white tracking-tighter uppercase">AI STUDIO</h1>
              <p className="text-gray-400">Generate visual artifacts for your Second Brain using Gemini 2.5 Flash.</p>
            </div>

            <div className="bg-white/5 border border-white/10 rounded-2xl p-6 backdrop-blur-md space-y-6">
              <div>
                <label className="block text-xs font-mono text-gray-500 uppercase mb-3">Manifest Prompt</label>
                <textarea
                  className="w-full h-32 bg-black/40 border border-white/5 rounded-xl p-4 text-white placeholder-gray-600 focus:outline-none focus:border-blue-500 transition-all resize-none"
                  placeholder="Describe your vision..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                />
              </div>

              <div>
                <label className="block text-xs font-mono text-gray-500 uppercase mb-3">Aspect Ratio</label>
                <div className="grid grid-cols-3 gap-2">
                  {['1:1', '16:9', '9:16'].map((ratio) => (
                    <button
                      key={ratio}
                      onClick={() => setAspectRatio(ratio)}
                      className={`py-2 rounded-lg text-xs font-bold border transition-all ${
                        aspectRatio === ratio 
                        ? 'bg-white text-black border-white' 
                        : 'bg-white/5 border-white/5 text-gray-400 hover:text-white'
                      }`}
                    >
                      {ratio}
                    </button>
                  ))}
                </div>
              </div>

              <button
                onClick={handleGenerate}
                disabled={isLoading || !prompt.trim()}
                className={`w-full py-4 rounded-xl font-black uppercase tracking-widest transition-all ${
                  isLoading || !prompt.trim()
                  ? 'bg-gray-800 text-gray-600 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-500 shadow-xl shadow-blue-500/20'
                }`}
              >
                {isLoading ? 'Processing...' : 'Generate Artifact'}
              </button>
            </div>
          </div>

          {/* Result - Right Column */}
          <div className="flex-1 w-full min-h-[600px] bg-black/40 border border-white/5 rounded-3xl flex items-center justify-center relative group overflow-hidden shadow-2xl">
            {isLoading && (
              <div className="flex flex-col items-center gap-4">
                <div className="w-12 h-12 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                <span className="text-blue-500 font-mono text-xs uppercase tracking-widest animate-pulse">Rendering...</span>
              </div>
            )}

            {!isLoading && !generatedImage && !error && (
              <div className="text-center opacity-20">
                <div className="text-9xl mb-4">🖼️</div>
                <p className="font-mono text-xs uppercase">Awaiting Input Signal</p>
              </div>
            )}

            {error && <div className="text-red-500 font-mono text-sm">{error}</div>}

            {generatedImage && (
              <div className="w-full h-full p-4 flex flex-col items-center justify-center">
                <img 
                  src={generatedImage} 
                  alt="AI Artifact" 
                  className="max-w-full max-h-[70vh] rounded-xl shadow-2xl object-contain animate-in fade-in duration-700"
                />
                <div className="absolute bottom-10 opacity-0 group-hover:opacity-100 transition-opacity">
                   <a 
                     href={generatedImage} 
                     download="ego-artifact.png"
                     className="px-6 py-3 bg-white text-black font-bold rounded-full shadow-2xl hover:scale-105 transition-transform"
                   >
                     Download Artifact
                   </a>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Studio;
